// front/src/components/auth/login.jsx
import { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { authService } from '../../services/auth.service';
import './Auth.css';

export const Login = () => {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const navigate = useNavigate();

  const handleLogin = async (e) => {
    e.preventDefault();
    try {
      const response = await authService.login(username, password);
      alert('Inicio de sesión exitoso');
      localStorage.setItem('token', response.token);
      navigate('/video');
    } catch (error) {
      alert('Usuario o contraseña incorrectos');
    }
  };

  return (
    <div className="auth-container">
      <div className="auth-box">
        <h2>Login</h2>
        <form onSubmit={handleLogin}>
          <input
            type="text"
            placeholder="Usuario"
            value={username}
            onChange={(e) => setUsername(e.target.value)}
            required
          />
          <input
            type="password"
            placeholder="Contraseña"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            required
          />
          <button type="submit">Iniciar Sesión</button>
        </form>
        <Link to="/register">¿No tienes cuenta? Regístrate</Link>
      </div>
    </div>
  );
};

// streaming/src/app/module/auth/login/login.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../../service/auth.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  username: string = '';
  password: string = '';

  constructor(private authService: AuthService, private router: Router) {}

  login() {
    this.authService.login(this.username, this.password).subscribe(
      (response) => {
        alert('Inicio de sesión exitoso');
        localStorage.setItem('token', response.token); // Guardar el token
        this.router.navigate(['/video']); // Redirigir al componente de video
      },
      (error) => {
        alert('Usuario o contraseña incorrectos');
      }
    );
  }
}

<div class="auth-container">
    <div class="auth-box">
      <h2>Login</h2>
      <input type="text" placeholder="Usuario" [(ngModel)]="username">
      <input type="password" placeholder="Contraseña" [(ngModel)]="password">
      <button (click)="login()">Iniciar Sesión</button>
      <a routerLink="/register">¿No tienes cuenta? Regístrate</a>
    </div>
  </div>
