// streaming/src/app/module/auth/register/register.component.ts
import { Component } from '@angular/core';
import { AuthService } from '../../service/auth.service';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent {
  username: string = '';
  password: string = '';

  constructor(private authService: AuthService) {}

  register() {
    this.authService.register(this.username, this.password).subscribe(
      () => alert('Usuario registrado exitosamente'),
      () => alert('Error al registrar el usuario')
    );
  }
}

<!-- Register -->
<div class="auth-container">
    <div class="auth-box">
      <h2>Registro</h2>
      <input type="text" placeholder="Usuario" [(ngModel)]="username">
      <input type="password" placeholder="Contraseña" [(ngModel)]="password">
      <button (click)="register()">Registrarse</button>
      <a routerLink="/login">¿Ya tienes cuenta? Inicia Sesión</a>
    </div>
  </div>

// front/src/components/auth/register.jsx
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { authService } from '../../services/auth.service';
import './Auth.css';

export const Register = () => {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const navigate = useNavigate();

  const handleRegister = async (e) => {
    e.preventDefault();
    try {
      await authService.register(username, password);
      alert('Usuario registrado exitosamente');
      navigate('/login');
    } catch (error) {
      alert('Error al registrar el usuario');
    }
  };

  return (
    <div className="auth-container">
      <div className="auth-box">
        <h2>Registro</h2>
        <form onSubmit={handleRegister}>
          <input
            type="text"
            placeholder="Usuario"
            value={username}
            onChange={(e) => setUsername(e.target.value)}
            required
          />
          <input
            type="password"
            placeholder="Contraseña"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            required
          />
          <button type="submit">Registrarse</button>
        </form>
        <Link to="/login">¿Ya tienes cuenta? Inicia Sesión</Link>
      </div>
    </div>
  );
};
